"""A/B listening preview (BUILD_PLAN.md GD4.5).

FIR is generated by the core's minimum_phase_impulse_response from the
current 10-band EQ curve, the test signal is convolved with
scipy.signal.fftconvolve and played through sounddevice. The A/B toggle
switches between the raw and equalized buffers at the playback cursor, so
the comparison is seamless.

The bundled test signal is pink noise (no licensing, spectrally flat per
octave — EQ changes are clearly audible on it).
"""

import threading

import numpy as np
from scipy.signal import fftconvolve

import eq_model
from autoeq.constants import DEFAULT_FS
from autoeq.frequency_response import FrequencyResponse

PREVIEW_SECONDS = 8.0
PREVIEW_LEVEL = 0.25  # RMS-ish target so pink noise isn't startling


def build_fir(bands: list, preamp_db: float = 0.0, fs: int = DEFAULT_FS) -> np.ndarray:
    """Minimum-phase FIR of the 10-band EQ curve (plus preamp), via the core."""
    f = FrequencyResponse.generate_frequencies()
    eq = eq_model.eq_curve(bands, f, fs)
    fr = FrequencyResponse(name="preview", frequency=f, equalization=eq)
    return fr.minimum_phase_impulse_response(fs=fs, normalize=False, preamp=preamp_db)


def pink_noise(seconds: float = PREVIEW_SECONDS, fs: int = DEFAULT_FS) -> np.ndarray:
    """Pink noise via 1/sqrt(f) spectral shaping of white noise."""
    n = int(seconds * fs)
    rng = np.random.default_rng(1)
    white = rng.standard_normal(n)
    spectrum = np.fft.rfft(white)
    freqs = np.fft.rfftfreq(n, 1 / fs)
    freqs[0] = freqs[1]  # avoid /0 at DC
    spectrum /= np.sqrt(freqs)
    pink = np.fft.irfft(spectrum, n)
    pink /= np.max(np.abs(pink))
    return (pink * PREVIEW_LEVEL).astype(np.float32)


class ABPlayer:
    """Loops a signal and its EQ'd version; set_eq() switches seamlessly."""

    def __init__(self, fs: int = DEFAULT_FS):
        self.fs = fs
        self._raw: np.ndarray | None = None
        self._eq: np.ndarray | None = None
        self._stream = None
        self._pos = 0
        self._eq_on = True
        self._lock = threading.Lock()

    @property
    def playing(self) -> bool:
        return self._stream is not None

    @property
    def eq_on(self) -> bool:
        return self._eq_on

    def prepare(self, bands: list, preamp_db: float, signal: np.ndarray | None = None):
        raw = signal if signal is not None else pink_noise(fs=self.fs)
        fir = build_fir(bands, preamp_db, self.fs)
        eq = fftconvolve(raw, fir, mode="full")[: len(raw)]
        peak = np.max(np.abs(eq))
        if peak > 1.0:  # keep headroom even with boosts
            eq = eq / peak
        with self._lock:
            self._raw = raw.astype(np.float32)
            self._eq = eq.astype(np.float32)
            self._pos = 0

    def set_eq(self, on: bool) -> None:
        self._eq_on = on

    def start(self) -> None:
        if self._stream is not None or self._raw is None:
            return
        import sounddevice as sd

        def callback(outdata, frames, time_info, status):
            with self._lock:
                buffer = self._eq if self._eq_on else self._raw
                n = len(buffer)
                idx = (self._pos + np.arange(frames)) % n
                outdata[:, 0] = buffer[idx]
                self._pos = (self._pos + frames) % n

        self._stream = sd.OutputStream(
            samplerate=self.fs, channels=1, dtype="float32", callback=callback
        )
        self._stream.start()

    def stop(self) -> None:
        if self._stream is None:
            return
        stream, self._stream = self._stream, None
        stream.stop()
        stream.close()
